ICOM - Comunicación, medios y mercadeo

Datos básicos
Año y mes de formación	2009 - 1
Departamento - Ciudad	BOGOTÁ, D. C. - BOGOTÁ, D.C.
Líder	Juan Camilo Ruiz Salazar
¿La información de este grupo se ha certificado?	Si el día 2019-06-10 00:00:00.0
Página web	https://ucompensar.edu.co/
E-mail	lfsanchezs@ucompensar.edu.co
Clasificación	B con vigencia hasta la publicación de los resultados de la siguiente convocatoria
Área de conocimiento	Ciencias Sociales -- Periodismo y Comunicaciones -- Medios y Comunicación Social
Programa nacional de ciencia y tecnología	Ciencia, Tecnología e Innovación en Ciencias Humanas, Sociales y Educación
Programa nacional de ciencia y tecnología (secundario)	Ciencia, Tecnología e Innovación en Tecnologías de la Información y las Comunicaciones

Instituciones
1.- FUNDACION UNIVERSITARIA COMPENSAR - (Avalado)

Plan Estratégico
Plan de trabajo: El plan de trabajo está fundamentado en las actividades del subproceso de investigación así: 1.Desarrollar proyectos de innovaciòn y desarrollo que respondan a las líneas propuestas por la facultad 2.Desarrollar nuevos programas de formación 3.Desarrollar contenidos de formaciòn empresarial 4.Participar en el afinazamiento de las competencias investigativas en la facultada con los semilleros de investigación A partir de los lineamientos generales lo que se propone para la facultad es: 1. Apropiaciòn del modelo D+I+C+A por parte de los investigadores con el fin de lograr un impacto en el sector productivo 2. Realizar los estudios de mercado y de impacto institucionales para cada uno de los mercados atendidos 3. Realizar propuestas de especialización para la facultad de comunicaciòn teniendo como soporte los estudios de mercado y de impacto en el sector productivo 4. Elaborar los programas de las asignaturas de mercadeo para las demás facultades teniendo como referente los campos de acciòn de los egresados y fortalecerlos en el conocimiento de los sectores propios de su desempeño. 5. Participar en la elaboración de las guias para las asignaturas de los nuevos curriculos. 6.Implementar el semillero de investigaciòn con un observatorio publicitario 7. Definir y consolidar las líneas de investigación apra los nuevos programas por ciclos propedéuticos
Estado del arte: En general se determinan las siguientes situaciones, las cuales están relacionadas con las actividades del mercadeo, la gestión comercial, la promoción y difusión de los productos y servicios: -Existe una necesidad en actividades para el mercadeo de los servicios, pues este sector registro el mayor número de empresas que se liquidaron antes de cumplir cuatro años de funcionamiento en actividades relacionadas con comercio al por mayor y al menor 39%, transporte almacenamiento y comunicaciones con un 12%, como las actividades más representativas. -Existe una gran dependencia del mercado interno en un 80%, tan sólo el 4% se dedica al mercado internacional -La principal debilidad, para más de la tercera parte de los empresarios es el tema relacionado con la formulación de la idea de negocio, la planeación y el direccionamiento estratégico de la operación de la empresa; es decir planeación estratégica al definir el modelo de negocios con un fuerte orientación al cliente. -Los empresarios tienen buen conocimiento sobre la competencia, la mayor parte tiene información del número, la localización y el tipo de productos y servicios ofrecidos por sus competidores. Sin embargo, una tercera parte no tiene información de aspectos importantes para la planeación del negocio como la estrategia de precios y los segmentos de clientes. -Los empresarios carecen de conocimiento y formación empresarial: las necesidades de capacitación se concentran en temas administrativos y gestión empresarial: las necesidades de capacitación se concentran en temas de administración de empresas, legales, mercados, clientes y competencia. -En la etapa de operación de la empresa, los empresarios identifican como un factor que incide en la liquidación, la falta de un plan de mercadeo y promoción de los productos y servicios. En efecto la mayor parte de los empresarios no realiza publicidad por medios masivos y se limita al la distribución de volantes, afiches y el envió de correos directos, medios
Objetivos: Consolidar las líneas de investigación del grupo a partir del desarrollo de proyectos y generación de productos, que respondan a las necesidades de cada programa académico, a las realidades del sector productivo y a los indicadores de Colciencias. Desarrollar estrategias que posibiliten la sostenibilidad financiera del grupo en términos de convocatorias, participación de proyectos y alianzas estratégicas. Fortalecer las competencias y capacidades técnicas, tecnológicas y del campo profesional y la formación investigativa del cuerpo docente, en función de dar respuesta a las necesidades identificadas en el sector productivo. Contribuir desde el grupo a la consolidación de estrategias de apropiación social del conocimiento, para el proceso de investigación de la institución. Generar alianzas interinstitucionales con el sector académico para impulsar la consolidación de redes de investigación. Fortalecer el semillero de investigación del grupo, como un espacio donde los estudiantes desarrollen sus competencias investigativas mediante la generación de proyectos, intercambio de experiencias y creando productos como resultado de los procesos de aprendizaje que puedan llegar a consolidar trabajos de grado. Consolidar el proceso de investigación formativa mediante la dirección y acompañamiento a los trabajos y proyectos de grado vinculando las temáticas para el fortalecimiento y dinámica de las líneas de investigación.
Retos: Implementar el modelo de investigación aplicada D+I+C+A para brindar soluciones empresariales e información útil en la toma de decisiones. Consolidar el grupo con reconocimiento académico, formativo y empresarial en las àreas de comunicación empresarial, publicidad, mercadeo y diseño.
Visión: Ser para el 2026 un grupo reconocido en el campo académico, formativo y empresarial de las áreas de la publicidad, el mercadeo, la comunicación y el diseño visual, debido a la pertinencia de los productos resultado de procesos y proyectos de investigación, a las necesidades del sector productivo y a la participación de la comunidad académica.

Líneas de investigación declaradas por el grupo
1.- Tendencias Publicitarias y nuevas tecnologías
2.- Comunicación, medios y Práctica social
3.- Diseño y gestión para la comunicación
4.- Tendencias de mercadeo y nuevas tecnologías.
